swagger: "2.0"
info:
  description: "Description"
  version: "1.0.0"
  title: "Shfuggiente SE 2"
host: "shfuggientese2.herokuapp.com"
basePath: "/api/v1"
schemes:
- "https"
- "http"
consumes:
- application/json
produces:
- application/json
paths:
  
externalDocs:
  description: "Find out more about Shfuggiente SE 2"
  url: "https://github.com/Fodark/shfuggiente_se2/wiki"
