swagger: "2.0"
info:
  description: "Description"
  version: "1.0.0"
  title: "Shfuggiente SE 2"
host: "shfuggientese2.herokuapp.com"
basePath: "/api/v1"
schemes:
- "https"
- "http"
consumes:
- application/json
produces:
- application/json
paths:
  /exams:
    post:
      tags:
      - "Exams"
      summary: "Add a new exam"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      # TODO: Add parameters
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Exam"
      responses:
        200:
          description: "Done"
        405:
          description: "Invalid input"
definitions:
  Exam:
    type: "object"
    required:
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "Exam 1"
externalDocs:
  description: "Find out more about Shfuggiente SE 2"
  url: "https://github.com/Fodark/shfuggiente_se2/wiki"
